# Generated by Django 4.0.5 on 2022-09-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='albumsName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.albums'),
        ),
    ]
